feat: add basic functionality

diff --git a/gh-make-commit b/gh-make-commit
--- a/gh-make-commit
+++ b/gh-make-commit
@@ -1,35 +1,50 @@
 #!/usr/bin/env bash
 set -e
 
-echo "Hello gh-make-commit!"
+# Determine if an gum is in the PATH
+if ! type -p gum >/dev/null; then
+  echo "gum not found on the system" >&2
+  exit 1
+fi
 
-# Snippets to help get started:
+commitTypes="fix\nfeat\ndocs\nstyle\nrefactor\ntest\nchore\nrevert"
 
-# Determine if an executable is in the PATH
-# if ! type -p ruby >/dev/null; then
-#   echo "Ruby not found on the system" >&2
-#   exit 1
-# fi
+scopeFile=$(pwd)/.scopes
 
-# Pass arguments through to another command
-# gh issue list "$@" -R cli/cli
+# verbose=""
+# name_arg=""
+# while [ $# -gt 0 ]; do
+#   case "$1" in
+#   --verbose)
+#     verbose=1
+#     ;;
+#   --name)
+#     name_arg="$2"
+#     shift
+#     ;;
+#   -h|--help)
+#     echo "Add help text here."
+#     exit 0
+#     ;;
+#   esac
+#   shift
+# done
 
-# Using the gh api command to retrieve and format information
-# QUERY='
-#   query($endCursor: String) {
-#     viewer {
-#       repositories(first: 100, after: $endCursor) {
-#         nodes {
-#           nameWithOwner
-#           stargazerCount
-#         }
-#       }
-#     }
-#   }
-# '
-# TEMPLATE='
-#   {{- range $repo := .data.viewer.repositories.nodes -}}
-#     {{- printf "name: %s - stargazers: %v\n" $repo.nameWithOwner $repo.stargazerCount -}}
-#   {{- end -}}
-# '
-# exec gh api graphql -f query="${QUERY}" --paginate --template="${TEMPLATE}"
+echo "Pick Commit Type"
+TYPE=$(echo -e $commitTypes | gum filter --no-strict )
+
+if test -f "$scopeFile"; then
+    echo "Pick Commit Scopes"
+    SCOPE=$(echo $scopeFile | gum filter --no-stric --no-lint )
+else
+    echo "Enter Commit Scopes"
+    SCOPE=$(gum input --placeholder "scope")
+fi
+test -n "$SCOPE" && SCOPE="($SCOPE)"
+
+echo "Enter Commit Summary"
+SUMMARY=$(gum input --value "$TYPE$SCOPE: " --char-limit=50 --placeholder "Summary of this change")
+echo "Enter Commit Details"
+DESCRIPTION=$(gum write --placeholder "Details of this change (CTRL+D to finish)")
+
+git commit -m "$SUMMARY" -m "$DESCRIPTION" -e
